import mongoose from "mongoose";

export const userSchema = new mongoose.Schema({
  name: String,
  username: String,
  password: String,
  courses: [{ type: mongoose.Schema.Types.ObjectId, ref: "Course" }],
});
export const adminSchema = new mongoose.Schema({
  name: String,
  username: String,
  password: String,
});

// ── Lesson subdocument (embedded inside Course) ───────────────────────────────
// Kept as a subdocument so no separate collection is needed.
// Each lesson has a stable _id generated by Mongoose.
const lessonSchema = new mongoose.Schema({
  title:       { type: String, required: true },
  description: { type: String, default: "" },  // Short summary shown above content
  content:     { type: String, default: "" },  // Full Markdown document
  order:       { type: Number, default: 0 },
});


export const courseSchema = new mongoose.Schema(
  {
    title: String,
    description: String,
    price: Number,
    imageLink: String,
    published: Boolean,

    adminId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Admin",
    },

    // ── Embedded lessons (LMS extension) ─────────────────────────────────────
    // Stored as subdocuments inside the course document.
    // Existing courses without this field default to an empty array.
    lessons: {
      type: [lessonSchema],
      default: [],
    },

    // ── New optional fields ──────────────────────────────────────────────────
    category: {
      type: String,
      enum: [
        "Web Development",
        "Frontend",
        "Backend",
        "Full Stack",
        "AI & Machine Learning",
        "Data Structures & Algorithms",
        "Database",
        "DevOps",
        "Cloud Computing",
        "Mobile Development",
        "Cyber Security",
        "Programming Languages",
        "Other",
      ],
      default: "Programming Languages",
    },
    level: {
      type: String,
      enum: ["Beginner", "Intermediate", "Advanced"],
      default: "Beginner",
    },
    language: {
      type: String,
      default: "English",
    },
    // Free-form string e.g. "12 Hours", "8 Weeks", "20 Lessons"
    duration: {
      type: String,
    },
    // Falls back to imageLink when not supplied at creation (handled in createCourses API)
    thumbnail: {
      type: String,
    },
    tags: {
      type: [String],
      default: [],
    },
    totalLessons: {
      type: Number,
      default: 0,
    },
    rating: {
      type: Number,
      default: 0,
    },
    studentsEnrolled: {
      type: Number,
      default: 0,
    },
  },
  {
    // Automatically manages createdAt and updatedAt
    timestamps: true,
  }
);




export const User = mongoose.models.User || mongoose.model("User", userSchema);

export const Admin =
  mongoose.models.Admin || mongoose.model("Admin", adminSchema);

export const Course =
  mongoose.models.Course || mongoose.model("Course", courseSchema);
